export const TYPES = {
    Logger: Symbol.for("Logger"),
    Config: Symbol.for("Config"),
    PaymentApp: Symbol.for("PaymentApp"),
    Test: Symbol.for("Test"),
    WalletRoute: Symbol.for("WalletRoute"),
    WatchersRoute: Symbol.for("WatchersRoute"),
    PaymentsRoute: Symbol.for("PaymentsRoute"),
    AppInfoRoute: Symbol.for("AppInfoRoute"),
    MessageBroker: Symbol.for("MessageBroker"),
    Metrics: Symbol.for("Metrics"),
    Kin: Symbol.for("Kin"),
    WalletService: Symbol.for("WalletService"),
    Database: Symbol.for("Database"),
    PaymentService: Symbol.for("PaymentService"),
    Watcher: Symbol.for("Watcher"),
    WatcherService: Symbol.for("WatcherService"),
    WhitelistRoute: Symbol.for("WhitelistRoute"),
    WhitelistService: Symbol.for("WhitelistService"),
    WatcherApp: Symbol.for("WatcherApp"),
    WatcherProcessor: Symbol.for("WatcherProcessor"),
    WorkerApp: Symbol.for("WorkerApp"),
    WalletCreator: Symbol.for("WalletCreator"),
    Locker: Symbol.for("Locker"),
    Axios: Symbol.for("Axios"),
    PaymentSender: Symbol.for("PaymentSender"),
    CallbackCaller: Symbol.for("CallbackCaller"),
};
